Additions
alekseik1/ifg-py pull request #16
Opened 2020-12-29 19:56 UTC by PavelRLevashov

2020-12-29 20:12 UTC, alekseik1 reviewed
Надо бы разобраться, почему тесты не проходят. На беглый взгляд кажется, что ничего в них не поменялось, поэтому и переводы должны оставаться правильными.

2020-12-29 20:12 UTC, alekseik1 commented on ifg/calculator.py
> +        Params.gbar = g * mr**1.5
Наверно, будет лучше это в поле записать: `self.gbar = g`

Соответственно, в функциях этот gbar надо будет принимать как параметр (предлагаю сделать значение по-умолчанию g=2)

2020-12-29 20:12 UTC, alekseik1 commented on ifg/calculator.py
> +class Params:
Думаю, лучше класс будет убрать и перенести в параметры функции эти значения

2020-12-29 20:34 UTC, alekseik1 requested changes

2020-12-29 20:34 UTC, alekseik1 commented on ifg/units_converter.py
> +            return energy / self.ha * self.ab3
Зачем умножать на `self.ab3`? Вроде, по размерности уже объем получается. Может, только делить на `self.ha`?

2020-12-29 20:34 UTC, alekseik1 commented on ifg/units_converter.py
> +            return energy * self.ha / self.ab3
Аналогично выше

2020-12-29 20:34 UTC, alekseik1 commented on ifg/units_converter.py
> +            return temperature / self.ha * self.kb
Тут порядок, проверил

2020-12-29 20:34 UTC, alekseik1 commented on ifg/units_converter.py
> +            return entropy / self.kb * self.ab3
Расхождение. Если не умножать на `self.ab3`, то будет равносильно предыдущему коду.
@PavelRLevashov почему нужно умножать на `self.ab3`?

2020-12-29 20:34 UTC, alekseik1 commented on ifg/units_converter.py
> +            return entropy * self.kb / self.ab3
Аналогично выше

2020-12-29 21:11 UTC, PavelRLevashov commented on ifg/calculator.py
> +        Params.gbar = g * mr**1.5
Значение по умолчанию g=2, в коде должно быть 
self.gbar = g * mr**1.5

2020-12-29 21:12 UTC, PavelRLevashov commented on ifg/units_converter.py
> +            return energy / self.ha * self.ab3
Энергия экстенсивная величина, ее нужно к чему-то относить. Здесь все такие величины относятся к объему, то есть размерность энергии в SI Дж/м^3

2020-12-29 21:13 UTC, PavelRLevashov commented on ifg/units_converter.py
> +            return energy * self.ha / self.ab3
Здесь обратное преобразование из атомной системы единиц в SI: сначала энергию переводим из Ha в Дж, а затем делим на единицу объема в атомной системе единиц.

2020-12-29 21:13 UTC, PavelRLevashov commented on ifg/units_converter.py
> +            return entropy / self.kb * self.ab3
Энтропия - экстенсивная величина

2020-12-29 21:15 UTC, PavelRLevashov commented on ifg/units_converter.py
> +            return entropy * self.kb / self.ab3
Аналогично энергии

2020-12-31 15:55 UTC, alekseik1 commented on ifg/calculator.py
> +class Params:
Сделал в cbd6fbb371429f8c8ceb5f646e06a01201a3fe18

2020-12-31 15:56 UTC, alekseik1 approved these changes

2020-12-31 16:00 UTC, merged